text = "Welcome to {name:>10} {surname}".format(name = "Milan", surname = "khimding")
text1 = "Namaste {}".format("Nepal")
text2 = "Namaste {1}".format("Nepal","Milan")
print(text)
print(text1)
print(text2)